### ISSUE TITLE
GenServer Reading: Typo/Partially missing sentence 

### ISSUE THREAD

**Issue by dr-acc** [DockYard-Academy/curriculum#1013]
**Describe the issue**
There seems to be a typo in the GenServer reading, perhaps a partial sentence was accidentally deleted.
It reads: "However some do not. of needed we can use ..." 

**Reproduction Steps (If Applicable)**
View GenServer reading 

**Expected behavior**
Expected complete sentences. I would edit if I felt sure of the intended meaning, but I am not totally sure what this was originally supposed to say. 

**Screenshots**
![Screenshot 2023-07-11 at 1 25 01 PM](https://github.com/DockYard-Academy/curriculum/assets/113741221/2d7e8208-bae4-49a2-8bdb-769d36bde71e)

**Comment by BrooklinJazz** [comment]
I am not sure what I was thinking when I wrote this. Thank you for tracking it. I've self-assigned and will modify it during my next review phase.
