### ISSUE TITLE
Automated capitalization applied incorrectly 

### ISSUE THREAD

**Issue by dr-acc** [DockYard-Academy/curriculum#1017]
**Describe the issue**
Caps on words "Raise" and "End" located in commented-out code in Supervisors reading 

**Reproduction Steps (If Applicable)**
See Livebook; code cell is under this paragraph: When a linked process crashes, it will also crashed the process that spawned it. Uncomment the code below, and you'll see it crashes the current Livebook process. Re-comment the code when finished.

**Expected behavior**
lower case lettering 

**Screenshots**
![Screenshot 2023-07-17 at 10 01 59 AM](https://github.com/DockYard-Academy/curriculum/assets/113741221/35065a2d-7c85-4b2b-bc48-06e0043f81c9)

**Comment by BrooklinJazz** [comment]
Yup. We have a script that caused a few of these bugs. It's on my TODO to fix it. Thank you for tracking this.
