### ISSUE TITLE
Numbering automation broken in "Blog: Posts" exercise

### ISSUE THREAD

**Issue by dr-acc** [DockYard-Academy/curriculum#1023]
**Describe the issue**
Numbering seems to be automated, but where steps should be identified with increasing numbers, the page only displays "1" repeatedly. 

**Reproduction Steps (If Applicable)**
Open "Blog: Posts" and view

**Expected behavior**
Expectations is for numbers to increase, thereby creating numbered steps/problems 

**Screenshots*
<img width="461" alt="Screenshot 2023-07-24 at 11 55 44 AM" src="https://github.com/DockYard-Academy/curriculum/assets/113741221/c7634dd0-9d58-4aae-936f-a068ec078082">
*

**Comment by BrooklinJazz** [comment]
Good catch. I think these used to be in order, so the markdown auto-incremented them. Then it broke when we added the example solutions.
