### ISSUE TITLE
Many-To-Many Relationships

### ISSUE THREAD

**Issue by stebbinsi2** [DockYard-Academy/curriculum#1030]
**Describe the issue**
In Join Table Migration, the unique index has a bit of a miss spelling

**Reproduction Steps (If Applicable)**
1. Go to Join Table Migration section
2. Go to    create(unique_index(:post_tags, [:post_id, :tag_id]))
4. See error: I believe is should be "posts_tags, ...."

![image](https://github.com/DockYard-Academy/curriculum/assets/135648032/294567c9-6d1d-4b5a-b4ff-60adf08e8345)

**Comment by BrooklinJazz** [comment]
That's correct. Good catch.
