### ISSUE TITLE
Fun Formulas tip calculator example is wrong give an answer of $30 total which should be $23 as the problem reads

### ISSUE THREAD

**Issue by Fursausage** [DockYard-Academy/curriculum#1054]
**Describe the issue**
A clear and concise description of the issue.

**Reproduction Steps (If Applicable)**

**Expected behavior**

**Screenshots**

**Comment by BrooklinJazz** [comment]
The solution looks fine to me

<img width="1171" alt="Screenshot 2024-03-21 at 11 56 21 AM" src="https://github.com/DockYard-Academy/curriculum/assets/14877564/41df5e79-6971-4629-886e-095e0795b4d9">
