### ISSUE TITLE
Update images to use the new files directory after livebook 0.11.0

### ISSUE THREAD

**Issue by scarolac** [DockYard-Academy/curriculum#1058]
**Describe the issue**
With livebook 0.11.0+, the images folder no longer loads images. There is a provided script they had on the release notes for 0.11.0 which links to this gist https://gist.githubusercontent.com/jonatanklosko/20e28aa772a888a25a829337a4b805e1/raw/a0da10fe5b45b09197529a76a08c92b9d80d8047/convert_notebook_images.exs

**Reproduction Steps (If Applicable)**
1. Go to any livemd file that links to an image in images/*.png/jpg
2. Livebook warning will show about this issue, and images from directory will not load

**Expected behavior**
The images should be in the files directory and load when you open the livemd file

**Comment by scarolac** [comment]
I was able to run this locally on the release file in the reading folder and it seems to work but may need more testing for an official update

**Comment by BrooklinJazz** [comment]
a PR would be very welcome! My plate has been very full on other projects a curriculum maintenance is on the backburner right now so I likely won't have time to make a PR myself for awhile but would happily test and approve a fixed version.

**Comment by andrew-pyle** [comment]
Are these changes (#1059) reflected in the [v2.0.0 release](https://github.com/DockYard-Academy/curriculum/releases/tag/V2.0.0)?

I downloaded the [Source Code from the releases page (.tar.gz)](https://github.com/DockYard-Academy/curriculum/archive/refs/tags/V2.0.0.tar.gz), and the [codemod script][1] did not seem to be applied.

When I opened the "Computer Hardware" LiveBook, I received an error from LiveBook indicating that images in the `images/` directory are deprecated. I confirmed that images are in the `reading/images/` directory and the `exercises/images/` directory.

I was able to manually apply the [codemod script][1], and the images appeared in the `files/` directory and appear in the LiveBook .

[1]: https://gist.githubusercontent.com/jonatanklosko/20e28aa772a888a25a829337a4b805e1/raw/a0da10fe5b45b09197529a76a08c92b9d80d8047/convert_notebook_images.exs

**Comment by scarolac** [comment]
no the 2.0 is the version i was using when i noticed the image issue, you could apply the same fix to the release, or build your own release with the updated changes on main
