### ISSUE TITLE
Animations show hidden "teachers only" (but they do work)

### ISSUE THREAD

**Issue by BigSpaces** [DockYard-Academy/curriculum#378]
Hello Brook,

Brief note to let you know that the animation cells appear with the message "hidden: teachers only". They do work, but I thought you'd like to know.

Is this the best way to report this type of things that I find as I go throught the curriculum, or is it better if we create a dedicated repository for feedback and suggestions as I move through the entire academy? I was talking to Andrew yesterday about finding a smooth way to direct feedback, corrections, and suggestions your way. Open to learning any way that works well :)

Thanks again,

BigSpaces

**Comment by BrooklinJazz** [comment]
Raising issues on the curriculum so far is working very well for me. Is it working for you?
We could also create a Discussions section on this repository 🤔

**Comment by BrooklinJazz** [comment]
Also, to address this issue I think I need to add warning to the `HiddenCell` library when the editor is open, that it's for teachers only, rather than including it in the title.

**Comment by BrooklinJazz** [comment]
There's only a single hidden cell in Arithmetic I need to fix.
