### ISSUE TITLE
Organize pages and exercise files by week number directory?

### ISSUE THREAD

**Issue by kianmeng** [DockYard-Academy/curriculum#382]
Saw this https://github.com/microsoft/Web-Dev-For-Beginners, perhaps we can follow how it organizes the course structure by week number? Something like:

```text
01_core_syntax
- 01_course_tools.livemd
- 02_basics.livemd
...
02_built-in_tools
...
```
What do you think?

**Comment by BrooklinJazz** [comment]
I've been thinking about moving away from time-based naming in general but am currently using it to better plan the material initially. That said, I like the idea of organizing the reading and exercises into folders.

I think we can revisit structuring the materials once all of the materials are complete.
The main reason is to optimize the speed of creating material. Having a flat structure means I don't have to move files and folders around if I need to move content around.

**Comment by BrooklinJazz** [comment]
Oh, I should mention some of the `utils` project depends on the file/folder structure. It shouldn't be too hard to fix, but wanted to document that thought for when we take action on this.

**Comment by BrooklinJazz** [comment]
Closing since we're launching cohort 1 and have now solidified the organization structure.
