### ISSUE TITLE
Suggestions and points of confusion in Keyword Lists and Maps

### ISSUE THREAD

**Issue by BigSpaces** [DockYard-Academy/curriculum#393]
Hello Brook,

I am reviewing maps and keyword lists and observing where my brain falls off a cliff, and what could be done in the explanation of the concepts to prevent that.

My first observation is to appeal to real-world examples, so the mind has a place where it can associate the concept, which otherwise feels too abstracted and not useful. Example:

![image](https://user-images.githubusercontent.com/113518695/192179696-1518d227-402b-4b9f-afd3-1d4f3ce31d5d.png)

I feel the concept would land better if, after "keys do not have to be unique", I would read something like "this is useful in X, Y, Z" situation. Also, providing a tangible example of when a keyword list is useful, could help.

I find this important because the following lesson is Maps, so putting the focus on the specific differences of function and use would (I guess) accelerate assimilation of concepts.

![image](https://user-images.githubusercontent.com/113518695/192180025-034a82f0-e879-46a9-86c7-5a1cce870469.png)

For example, you write "they can have atoms" as keys. But all the examples so far are with atoms, so my mind gets initially confused: "can have atoms? should have atoms? they normally have atoms? in which case they don't? what's an example?" - I sense that my brain is trying to find the specific differences between maps and keyword lists but the explanations are so high-level and abstract that it has a hard time.

Something similar happens when I read "keys must be unique", and my mind goes... "wait a sec, so..." (and I go back to Keyword Lists to see if I can understand the use of not enforcing unique keys in Keyword Lists, and how that makes for a different use).

In the case of tuples and lists, my mind "clicked" when I thought of tuples as X, Y, Z coordinates on a map, and a list as a spotify playlist or a list of my favorite books. When it comes to Keyword Lists and Maps, I find that my mind is looking for that type of specific example that would help bring the abstract concept down to earth, as to remember it (1) and understand its practical use (2).

I hope this helps!

**Comment by BrooklinJazz** [comment]
Great points. I'll circle to this when I have the bandwidth to review. I completely agree that providing some context for WHY we use atom keys and providing some more real-world examples would help tremendously.
