### ISSUE TITLE
Please Add Link to Prior Section

### ISSUE THREAD

**Issue by tindrew** [DockYard-Academy/curriculum#419]
**Describe the issue**

Pretty please add a link to each section at the top of the page to go back to the prior section. It would help when I just need to flip back a quick section to check something without having to scroll all the way through the content first. Thanks!

**Comment by pascalwengerter** [comment]
@BrooklinJazz I see the exercises have a "go to previous" link at the bottom, would you like me to open a PR and add the same for the top?

**Comment by BrooklinJazz** [comment]
Definitely! Instead of manually fixing this, it would be fantastic to add it to our existing `add_navigation` script.

**Comment by pascalwengerter** [comment]
I'd like to work on that one, could you specify where exactly to put it (above/below the main heading)?

**Comment by BrooklinJazz** [comment]
It makes sense to me to modify the existing navigation section to include these links.

**Comment by BrooklinJazz** [comment]
Closing this as we have navigation at the bottom now.

I can see us re-opening this if folks request we add navigation at the top as well.
