### ISSUE TITLE
Add more examples to Caesar Cypher exercise

### ISSUE THREAD

**Issue by BrooklinJazz** [DockYard-Academy/curriculum#506]
Currently it's unclear only using the alphabet as an example. It misled the students to think they were shifting the string.

**Comment by BrooklinJazz** [comment]
Also brooklin cannot spell and does not know his ABCs. Correct the alphabet.

**Comment by threetriangles** [comment]
Was this exercise an example of bit shifting?

**Comment by BrooklinJazz** [comment]
Hmm, In this case, I don't think so. We're using the codepoints for each character, not manipulating bits.

However, that could perhaps be one solution (I haven't done much bit manipulation so I'm not 100% if this could be used but it looks like it). However, it's not the intended learning outcome.
