### ISSUE TITLE
Correct `string()` type use in Typespec Drills exercise

### ISSUE THREAD

**Issue by SRFowler** [DockYard-Academy/curriculum#540]
In the file exercises/typespec_drills.livemd in the "Custom Types" exercise the Example Solutions use a typespec of `string()` which throws a warning of:
> warning: string() type use is discouraged. For character lists, use charlist() type, for strings, String.t()  
  
These suggestions should be updated to `String.t()` in keeping with the warning and previous exercise.

**Comment by BrooklinJazz** [comment]
Correct! Good catch.
