### ISSUE TITLE
Fix typo in Pascal's triangle representation as a list of lists

### ISSUE THREAD

**Issue by BhargavaSwamy** [DockYard-Academy/curriculum#545]
**Describe the issue**
Pascal's triangle, when represented as a list of lists, does not match the diagram representation 

**Expected example**
>[[1], [1, 1], [1, 2, 1], [1, 3, 3, 1], [1, 4, 6, 4, 1]]

**Current example**
>[[1], [1, 1], [1, 2, 1], [1, 3, 3, 1], [1, 3, 6, 3, 1]]

**Comment by BrooklinJazz** [comment]
Great catch! Going to leave this as a good first issue.
