### ISSUE TITLE
 GenServer API Section could add an evaluation cell

### ISSUE THREAD

**Issue by IciaCarroBarallobre** [DockYard-Academy/curriculum#593]
**Describe the issue**
Maybe calling GenServer API Section could add an evaluation cell like:

```elixir
{:ok, pid} = CounterClientAndServer.start_link([])
CounterClientAndServer.increment(pid)
```

**Screenshots**
![image](https://user-images.githubusercontent.com/47258107/201424633-aea827bd-a8ee-4742-8548-9e4782b7bfdc.png)

**Comment by BrooklinJazz** [comment]
I definitely agree! Going to open this up as a good first issue for anyone looking to make a PR.
