### ISSUE TITLE
Document Tools doctest lines for `add_line_numbers` has a typo.

### ISSUE THREAD

**Issue by w0rd-driven** [DockYard-Academy/curriculum#615]
In the exercise [Document Tools](https://github.com/DockYard-Academy/beta_curriculum/blob/main/exercises/document_tools.livemd), it appears there is a typo in the example documentation for the `add_line_numbers` function.

The text `iex> File.write("add_line_numbers.txt", "one\n\ntwo\nthree")` will create a blank line as line number 2 due to the two back to back `\n\n` line endings.

The expected text to make the example solution pass would be `iex> File.write("add_line_numbers.txt", "one\ntwo\nthree")`.

I should be at my computer later tonight to make a PR for this change. I just needed to create something or I would possibly forget.

**Comment by BrooklinJazz** [comment]
If you have time to make a PR that would be awesome! If not this would make a great first issue.
