### ISSUE TITLE
Fix modules.livemd "(Compile Error)module already defined"

### ISSUE THREAD

**Issue by srgarner** [DockYard-Academy/curriculum#622]
Issue:
On the examples of Greeter, InspectorGadget, Speaker/Listener, MyModule the 2nd time these are written into the smartcells and evaluated causes the "Module already defined" error. 

This may be sort of distressing to completely new programmers.

To get around it, I just changed to Greeter2, InspectorGadget2, etc... because I realized this is happening, because all the smart cells are working together basically as 1 .exs file.

Possible solution: Adding numbers to the repeated Module names ( with explanation). [Unless this is somehow a deprecated feature, for which it could be explained that reassigning modules is possible in future versions of Exlir.]

**Comment by BrooklinJazz** [comment]
There was a recent update to Livebook that I believe caused this issue. I notice this happening recently, thank you for raising this issue we will need to adjust all reading material that builds up the same module name.

Alternatively, we might be able to raise an issue on Livebook and see if they can resolve the problem.

**Comment by BrooklinJazz** [comment]
To resolve this issue, I think we should write a script that makes sure there are no modules inside of a lesson with the same name 🤔 It would have to make sure it doesn't catch modules in a markdown block, only in an actual Elixir cell.

**Comment by jonatanklosko** [comment]
Hey @BrooklinJazz! As of https://github.com/livebook-dev/livebook/pull/1518 it is now expected that a module is defined only in a single cell and cannot be redefined later on. So to fix the examples you need to use unique names :)

**Comment by BrooklinJazz** [comment]
> Hey @BrooklinJazz! As of https://github.com/livebook-dev/livebook/pull/1518 it is now expected that a module is defined only in a single cell and cannot be redefined later on. So to fix the examples you need to use unique names :)

Thank you for the confirmation, We'll update the  material to fix it!

**Comment by BrooklinJazz** [comment]
Fixed in #711
