### ISSUE TITLE
Add reading time to each Livebook

### ISSUE THREAD

**Issue by w0rd-driven** [DockYard-Academy/curriculum#655]
What spurred this was the dense reading material in https://github.com/braytonium/beta_curriculum_changes/blob/main/reading/book_search_books.livemd. It would likely be highly useful to have a `Reading time - 5 mins` section like https://fly.io/phoenix-files/phx-gen-auth/. `Reading time 5 minutes Return Home Report an Issue` all together feels a little cluttered but I'm indifferent to the UI. Perhaps wrapping the section in a flexbox to push the links to the far right, or making them equal spacing could be okay.

This is possibly an intermediate PR because it would likely require altering the top-level navigation. While we're here we could also adjust the `Report an Issue` link with a format that identifies the filename or a meaningful title.

A good example of a reading time function to nab would be https://github.com/dbernheisel/bernheisel.com/blob/main/lib/bern/blog/post.ex#L39. There are other ways of splitting word boundaries but `round(words / average words per minute)` is a seemingly straightforward formula to implement. The real work would be injecting the section cleanly but there are likely other examples for that in the `utils/lib/mix/tasks/` directory.

I may have time to do this but I feel quite a bit behind so I wanted to outline what I think it could look like. I think this would be beneficial for practically all the notebooks, including the outline.

Livebook itself may benefit from this request as a part of all notebooks. Obsidian has it as a community plugin that is a little more configurable. I may raise this as a discussion there but it may not be implemented.

**Comment by BrooklinJazz** [comment]
Marking this as `wontfix` for cohort 1, but anyone is welcome to tackle this.

**Comment by w0rd-driven** [comment]
I'm not 100% sure really. Obsidian has it as part of a status bar in the bottom right corner of the screen that shows a word count and row/column count I think. That's my pipe dream version.

A smart cell is nice but I guess those can be styled any way imaginable. I never looked into how difficult it would be to evaluate all cells that way. The blog implementation naively splits on spaces and I don't know if Livebook handles more complex code to give an inaccurate representation due to an abundance of different whitespace.

My initial implementation would've been a Mix task since navigation is injected. A styled yet configurable smart cell or change to Livebook could benefit more of the ecosystem. Now that I think about it further, a smart cell would be able to detect the code students are entering, which would change the results if usually slightly. I think the mix task is still a good first pass just that could be shaped to a version the curriculum could use. It would also be a little more nimble to changes. We could always extract a smart cell idea from that. Not covering student changes could be enough of a blocker though. I can't recall how often I changed the reading material where this is most needed.

**Comment by SRFowler** [comment]
Here’s how Medium does their calculation. 
I would recommend using a lower WPM reading rate, given the technical nature of the material and  the target audience being new to the concepts and thus needing to re-read many things. Maybe 180-200 wpm.
I concur that generating this data with the navigation at build time is probably the best method.
Af a first pass simple division is probably fine. You may want to add a few seconds per heading `##` as well. On a second iteration split word counts into two bins, one for text and one for code, and set the expected WPM for code a bit lower.  

Personally I would error toward an overestimation on reading time, again due to the specific nature of the material. If we overshoot the time and most students are finishing the material in 80% - 90% of the estimation it’s encouraging as opposed to seeing a number and taking an additional 20% to finish.

**Comment by BrooklinJazz** [comment]
I agree with making a mix task. We can add it to the existing `bc` tasks (which is in need of a rename  now!)

I don't think this will make it into the first cohort, but it could be a great one for the next cohort after!

**Comment by BrooklinJazz** [comment]
We may want to only calculate read time for the non-repeated sections (marking as completed, git commit) however, each of these includes a time-consuming action so maybe it's appropriate to include them in 🤔

**Comment by w0rd-driven** [comment]
What you said made my brain go on this tangent but time to read the text is not the same as estimated time to complete the material. I don't think that's what you meant. The latter would stress me out as part of the material. I have a personal desire to create take home assignment practice exercises where even very loose estimates would be helpful.

I can also see where wpm is maybe for only people where English is their first language. I personally find it useful to know length of something because I know if it's a 30 minute read I have to practically schedule time for it.

I think it could also potentially be more useful as a creator. The mix task could warn for text over a threshold like 5 minutes, or you could have a Livebook dashboard that sorts the results for each file in a Kino table. You'd potentially be able to notice anomalies. I have no clue what spells you used to keep it all as tight as it is and this does feel a bit late. I could see this useful for n+1 or anyone creating similar curriculum from scratch.

**Comment by BrooklinJazz** [comment]
Maybe a non-time based note would be useful.

I.e. short, medium, long or something similar. The #1 benefit of this that I see for the student is to avoid any sudden surprises that a reading is abnormally long so they don't feel last-minute pressure to get it done in time.

**Comment by BrooklinJazz** [comment]
Interesting that could also be useful for writers 🤔

**Comment by BrooklinJazz** [comment]
That would make making this a smart cell more appealing 🤔 easier to include in any project than a task or script.
