### ISSUE TITLE
BookSearch: Deployment setup-ci requires Personal Access Token

### ISSUE THREAD

**Issue by GumptionWare** [DockYard-Academy/curriculum#674]
My GitHub credentials lacked a Personal Access Token with the `workflow` scope enabled. This produced the following error when attempting a `git push` to my clone of BookSearch:
```
To https://github.com/GumptionWare/BookSearch.git
 ! [remote rejected] setup-ci -> setup-ci (refusing to allow a Personal Access Token to create or update workflow `.github/workflows/test.yml` without `workflow` scope)
error: failed to push some refs to 'https://github.com/GumptionWare/BookSearch.git'
```
I recommend adding a sidebar (or something like that) noting that this will likely be an error new GitHub users will encounter. The fix is described here: https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token#using-a-token-on-the-command-line

In my case, I had a personal access token defined, but it did not have the `workflow` scope. In hindsight, I could have simply edited that token to enable `workflow`:
<img width="804" alt="Screen Shot 2022-12-28 at 12 49 06 PM" src="https://user-images.githubusercontent.com/15247116/209882402-c9717a60-eae0-40a7-82ee-67cf3a7a269a.png">

Instead, I created a new personal access token, then I needed to go edit the authentication used by GitHub via (for MacOS) the Keychain Access tool. In Windows, this would likely require Registry edits.

So best bet if someone already has a personal access token: Edit it.

**Comment by BrooklinJazz** [comment]
Thank you for catching this. We should include a troubleshooting section in the material.
