### ISSUE TITLE
Consider an exercise for working with excel speadsheets

### ISSUE THREAD

**Issue by BrooklinJazz** [DockYard-Academy/curriculum#709]

**Comment by BrooklinJazz** [comment]
I don't think I'll add this for the first cohort, but it may be something we come back to.

**Comment by SRFowler** [comment]
Would this be for a generic CSV or for a more spreadsheet specific format like OpenXML( .xlsx )?

**Comment by BrooklinJazz** [comment]
I was thinking a generic CSV file.
