### ISSUE TITLE
Nixkpgs defaults to version 1.13.4 

### ISSUE THREAD

**Issue by Xel** [DockYard-Academy/curriculum#736]
Nixpkgs is a bit behind, so attempting to drop in via the derivation of the build environment you provided in your flake.nix isn't possible.

 Apparently, livebook only runs on Elixir ~> 1.14.2 or ~> 1.15-dev?

**Comment by BrooklinJazz** [comment]
I think we should remove the flake. It was added to support people using it by other people using it.

I'm not a flake user, though, and I don't think we should support it since it's likely to fall behind without an active maintainer using it.

**Comment by BrooklinJazz** [comment]
Flake has been removed

**Comment by Xel** [comment]
Sad to see the flake go, but I understand.
