### ISSUE TITLE
RPG Dialogue grammar error

### ISSUE THREAD

**Issue by einariii** [DockYard-Academy/curriculum#776]
**Describe the issue**
Extraneous word "may" in the sentence on line 24 of the "Bonus: Character Instances" cell of the RPG Dialogue exercise:

> Use _may_ these three structs to test your Character functions.

**Expected behavior**
Should read as: 

``Use these three structs to test your Character functions.``

![image](https://user-images.githubusercontent.com/90233563/216441436-76a56c05-aa96-4ba8-a466-7859d52e0b89.png)

**Comment by BrooklinJazz** [comment]
Making a PR would be appreciated, but capturing it with an issue is also great. That way we don't miss it if you don't have time to make a PR.

**Comment by opanye** [comment]
Roger. In future will go the PR route instead!

**Comment by BrooklinJazz** [comment]
> 

Raising an issue is still fantastic! I usually still recommend raising an issue since it's faster than a PR and captures the problem for you or someone else to fix later.
