### ISSUE TITLE
Structs grammar error

### ISSUE THREAD

**Issue by einariii** [DockYard-Academy/curriculum#777]
**Describe the issue**
Extraneous word "create" in the following sentence in the Structs reading material:

> When finished create bind a variable `hero` to an instance of your `Hero` struct.

**Expected behavior**
Should read as: 

``When finished bind a variable `hero` to an instance of your `Hero` struct.``

![image](https://user-images.githubusercontent.com/90233563/216442987-10ddb3b9-f09a-413d-9039-fff077e450ec.png)

**Comment by BrooklinJazz** [comment]
Great catch! Sorry for the super late response. Marking this as a good first issue.
