### ISSUE TITLE
Markdown code formatting looks like code cells

### ISSUE THREAD

**Issue by mvkvc** [DockYard-Academy/curriculum#779]
In the exercises when given a problem, usually there are some inputs that are formatted in markdown. However they look like code cells and so you expect to be able to use them in your code which is not true as you need to copy and paste them into your code cell.

**Comment by BrooklinJazz** [comment]
If there isn't any issue with running the cells we should just replace them with Elixir cells instead.

However, sometimes it's best for them to be markdown cells and there's no way of getting around that they look like code cells.

**Comment by BrooklinJazz** [comment]
@mvkvc would you be interested in grabbing this issue and making a PR? I know your plate is full so no pressure.

**Comment by mvkvc** [comment]
Sure I'll do it today in class when I have some time.
