### ISSUE TITLE
Multiple Arguments and Params "exercise" should be more concise

### ISSUE THREAD

**Issue by amir-repository** [DockYard-Academy/curriculum#799]
**Describe the issue**
On the first try I'm confuse about what should I do since the desired action is to call the call function inside the MultiParamExample

**Reproduction Steps (If Applicable)**
1. Go to Module section
2. Check you turn in Multiple Arguments and Params

**Screenshots**
![image](https://user-images.githubusercontent.com/37258290/218476261-4630ab2f-a8e1-4abd-8f92-c47c19155021.png)

**Comment by BrooklinJazz** [comment]
I've simplified the explanation and removed the existing call to make the desired action clearer and less redundant.
