### ISSUE TITLE
Livebook Shortcut Change

### ISSUE THREAD

**Issue by TheGriffinCircus** [DockYard-Academy/curriculum#811]
Looks like Livebook updated their keyboard shortcuts. Under the Reading assignment for Livebook (Core Syntax>Course Tools>Reading).

The Setup section discusses that the intended way to evaluate a cell is to use `ea` as the keyboard shortcut.

The correct keyboard shortcut is `ee` instead. 

Looking at the Github changes (I'm new to this so bare with me) it appears to have been changed during [Enable HEEx formatter (Issue #1322)](https://github.com/livebook-dev/livebook/commit/3fcb6b97bb325d6fad8b49d9052d35fb78c53370)https://github.com/livebook-dev/livebook/pull/1322[)](https://github.com/livebook-dev/livebook/commit/3fcb6b97bb325d6fad8b49d9052d35fb78c53370) on Aug 2, 2022.

**Comment by TheGriffinCircus** [comment]
Closing this issue, as user (this user's) error. Further review as I was going to submit a pull request to correct the changes, realized ``ea`` is used for evaluating all outdated cells and ``ee`` is used for evaluating a cell.  

This issue is unfounded and I apologize for submitting it.

**Comment by BrooklinJazz** [comment]
No apology is needed! Thank you for reviewing the content.
