### ISSUE TITLE
RPG Dialogue - Doctest Failure

### ISSUE THREAD

**Issue by matt-humphrey** [DockYard-Academy/curriculum#816]
I implemented a solution (which I verified with the example solution) for the exercise, but the second doctest was not passing.
I believe it's because it expects an ArgumentError because a name is required, but there's no error in the test because a name is given in the example.

Even when testing with the example solution, the same problem occurs.

By changing the doctest to the following: `iex> %Character{}`, the expected output occurs, but the doctest doesn't pass, it simply outputs the error.

**Screenshots**

The below two images depict the current issue:

![image](https://user-images.githubusercontent.com/34499789/220258993-c55b7495-3819-4f04-abe6-83acb5ec7764.png)

![2023-02-22_09-09](https://user-images.githubusercontent.com/34499789/220521232-ebff999c-0e3e-4c00-8e7a-496f45f28497.png)

By changing the second doctest to `iex> %Character{}`, the output is:

![image](https://user-images.githubusercontent.com/34499789/220521488-f8eb6f39-10e5-4885-a40d-dea7ef0be311.png)

**Comment by BrooklinJazz** [comment]
Why do I feel I incorrectly fixed this issue and caused this bug 🤔 (probably because I did!)

Thank you for reporting the error. Marking this as a good beginner issue.

**Comment by amir-repository** [comment]
> Why do I feel I incorrectly fixed this issue and caused this bug thinking (probably because I did!)
> 
> Thank you for reporting the error. Marking this as a good beginner issue.

Btw, is it a compiler error? hence the doctest could not catch it, I don't exactly sure what's happened so I asked it on stackoverflow.
[Link here](https://stackoverflow.com/questions/75467345/elixir-doctest-failed-to-catch-error-on-struct-with-enforced-keys?noredirect=1#comment133155760_75467345)

**Comment by BrooklinJazz** [comment]
Yes! It's a compile error, so the tests can't run properly until the student defines the struct.

Unfortunately, I don't think it's possible for us to get around this. Either we have to omit the doctests or accept that the doctests won't run until the student defines the struct keys.

Alternatively, we could request that Livebook changes how they handle doctests that fail to compile and see if it interests them 🤔

**Comment by amir-repository** [comment]
Yeah I think it's way better if we propose changes on Livebook about this since it will benefit more users if it possible, but when it is not, we should remove it (or maybe there's a better way instead of removing it), does this sounds good?

**Comment by matt-humphrey** [comment]
Bump on this. I agree with Amir that while it's not possible with Livebook, we should omit the failing doctests (I've seen a couple in other notebooks also).

**Comment by BrooklinJazz** [comment]
The OTP section has a lot of issues like this. I'm going to raise A single larger issue for this problem and we can try to solve it universally.
