### ISSUE TITLE
Fix doc tests in Metric Conversion bonus exercise under  Advanced Pattern Matching

### ISSUE THREAD

**Issue by lgmfred** [DockYard-Academy/curriculum#818]
The `Metric.convert/2` function is supposed to always return a float.

![image](https://user-images.githubusercontent.com/30313228/220316064-b27236b5-223f-46b0-961b-d44463d028ea.png)

But some doc tests (2 in particular) return integers

![image](https://user-images.githubusercontent.com/30313228/220317222-5dd857f8-b96c-4b8f-9e08-5f1c822e345b.png)
![image](https://user-images.githubusercontent.com/30313228/220317768-0168852d-31f5-43af-b703-44f0a40daad8.png)

**Comment by BrooklinJazz** [comment]
Good catch! Marking as good first issue.
