### ISSUE TITLE
Navigation missing on pages

### ISSUE THREAD

**Issue by mvkvc** [DockYard-Academy/curriculum#834]
**Describe the issue**
There is not bottom navigation in the page

- [ ] [built-in_modules](https://github.com/DockYard-Academy/curriculum/blob/main/reading/built-in_modules.livemd)
- [ ] [tic_tac_toe](https://github.com/DockYard-Academy/curriculum/blob/main/exercises/tic-tac-toe.livemd)
- [ ] [tic_tac_toe](https://github.com/DockYard-Academy/curriculum/blob/main/exercises/drill-patternmatching-replace-nils.livemd)
- [ ] [streams](https://github.com/mvkvc/dockyard_academy/blob/main/reading/streams.livemd) (next module name is incorrect should to `stream drills` not `streams`)

**Reproduction Steps (If Applicable)**
1. Go to 
3. Scroll down to the bottom

**Expected behavior**
Navigation links to the next and previous page

**Comment by mvkvc** [comment]
Are these added manually or with a script?

**Comment by BrooklinJazz** [comment]
It uses a script. You can run `mix bc` to add all navigation. It worries me that the script isn't handling these 🤔

**Comment by BrooklinJazz** [comment]
I have to look into this when I have some more time

**Comment by BrooklinJazz** [comment]
This has been resolved
