### ISSUE TITLE
will will -> will

### ISSUE THREAD

**Issue by lgmfred** [DockYard-Academy/curriculum#859]
**Score Tracker** exercise under **Asynchronous Messages**

![image](https://user-images.githubusercontent.com/30313228/222545812-4fae919b-b37a-4e0a-bb48-f2df69c59050.png)

**Comment by BrooklinJazz** [comment]
good good catch catch

**Comment by TheGriffinCircus** [comment]
This seems in my wheelhouse and would like to take it on unless someone else wanted to do it?

**Comment by Mraiih** [comment]
@BrooklinJazz seems like the issue didn't close correctly 🤔

**Comment by BrooklinJazz** [comment]
> @BrooklinJazz seems like the issue didn't close correctly 🤔 

Thank you!
