### ISSUE TITLE
Mention alternative to Google fonts in HTML/CSS module

### ISSUE THREAD

**Issue by mvkvc** [DockYard-Academy/curriculum#865]
When discussing fonts for styling, the only example given is the usage of Google Fonts. While it is popular and should be mentioned, there are privacy concerns as all visitors' IP addresses are transmitted to Google whenever they visit your site. This has been found to be violating the GDPR in this [case](https://rewis.io/urteile/urteil/lhm-20-01-2022-3-o-1749320/) (english summary [here](https://blog.runcloud.io/google-fonts-gdpr/)).

I propose a short markdown block with a disclaimer about what is collected and instructions or at least a link to a resource on how to download and load fonts locally. I am willing to submit a PR for this if you agree @BrooklinJazz.

**Comment by BrooklinJazz** [comment]
Yucky. I didn't know that. I 100% agree. I would also consider adding some alternatives. I just happen to be most familiar with Google fonts but i am not married to them in any way.

**Comment by mvkvc** [comment]
Ok I will draft a PR soon when I have some time and keep it concise. I'm open for anyone else to help out as well.

**Comment by mvkvc** [comment]
The best option from my research is downloading the font into your project and using the `@font-face` CSS rule ([link](https://css-tricks.com/snippets/css/using-font-face-in-css)). For the material on tailwind, there is some guidance in the docs ([link](https://css-tricks.com/snippets/css/using-font-face-in-css/)). I want to mention this here in case someone else has more experience and knows a better solution.

**Comment by BrooklinJazz** [comment]
Great, I'm down to completely replace the Google Fonts instruction with downloading and using @font-face.

I'm also fine with simply explaining web-safe fonts and then linking to an external resource for using @font-face.
