### ISSUE TITLE
Inconsistency in CounterWeb.CounterController function names

### ISSUE THREAD

**Issue by lgmfred** [DockYard-Academy/curriculum#882]
**Phoenix 1.7 reading material**

In the **Router** subsection, a  `"/counter"` route was set up for the `counter` application with the atom `:count`.

![image](https://user-images.githubusercontent.com/30313228/224272229-4b49b48b-0dd9-43fe-9286-d68412676ac8.png)

In the **Controller** subsection:

Isn't the name of the controller function in the `CounterController` module supposed to be consistent with the atom above? The function is initially defined with the correct name.

![image](https://user-images.githubusercontent.com/30313228/224268960-6f4fc323-88ad-4026-ab41-7a7e9c6143a5.png)

But then, subsequent descriptions and examples keep referring to `CounterController.index/2` instead of `CounterController.count/2`

**Comment by BrooklinJazz** [comment]
resolved in #941
