### ISSUE TITLE
Wrong naming on generated _build folder?

### ISSUE THREAD

**Issue by amir-repository** [DockYard-Academy/curriculum#887]
**Describe the issue**
There's an inconsistent naming for folder structure about _build folder in the docs, I don't know if it make any difference on dev or prod, but on my machine there will be like _build/dev/ebin not _build/ebin

**Reproduction Steps (If Applicable)**
1. Go to Mix sections
2. Jumps to Mix.exs section

**Expected behavior**
A correct folder structure based on real device

**Screenshots**
![Screenshot from 2023-03-14 07-54-57](https://user-images.githubusercontent.com/37258290/224865195-d8faa9ba-dee1-4a7c-9f4c-8a0aed43d73d.png)

**Comment by BrooklinJazz** [comment]
It might be wrong in the reading. If someone wants to address this I would be happy to either:
1. Change the path to include `dev`
2. Simply remove this part of the material as it's not crucial.
