### ISSUE TITLE
We can the records --> We can read the records

### ISSUE THREAD

**Issue by lgmfred** [DockYard-Academy/curriculum#896]
**Relational Database Management Systems** reading material

![image](https://user-images.githubusercontent.com/30313228/225624986-c3376822-329b-4045-bd9b-8e2bd0f72741.png)

**Comment by Mraiih** [comment]
@BrooklinJazz Should be good to close now (it's not automatic when linked PR are merged? Did I miss something? 🤔 )

**Comment by BrooklinJazz** [comment]
The exact wording matters.

For example, the following all work.
fix #896
close #896

**Comment by BrooklinJazz** [comment]
See here: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword
