### ISSUE TITLE
Bonus Topic Ideas

### ISSUE THREAD

**Issue by BrooklinJazz** [DockYard-Academy/curriculum#902]
Comment on this issue if you have ideas for extra topics we could cover in the course that might not be suited for the core curriculum.

Here are a few of mine (in no particular order):
* Nested Forms (inputs_for)
* [X] Registry #907
* [X] Poolboy #907 
* [ ] Exceptions and error handling
* [ ] Coveralls (test coverage)
* [ ] Problem Solving and Debugging
   * dbg and other debugging (how to read errors)
   * shine the light on the code
   * using the inspector to debug CSS + HTML.
   * observer
* [ ] Circular Buffers 
* [ ] Advanced Livebook + Mermaid (add [mermaid live editor](https://mermaid.live/edit#pako:eNqNUrFOwzAQ_ZWTJ0DtwOqBiZWJMtWoOuJrYik-R_YFqKr-O3bsCrKgTnl-93zv3cVn1QVLSqtuxJSeHfYRvWGA5Qy7IRJaOBcGQJbTwVkNzlbKUuqim8QF1pAkOu5rgdHTmvGUEvaUNOxfKnw33Bq7XBT0U7q7L8zlN0GTXiO0JqsMXWAhFg07-pa_SXXLX7lEbClqeEsU4QbnRdds54xXnuTRjev5BkwD2cOU736FaNfFnPHoos91zEEZ3ScdLAoV_3-ylE_7B0Y9GgXb7VNGDxldF6OLMXjkUxFf2aorN5YxNHzQGLhPIKHI6g5u6Kg2ylPMw9r8RpZlGCUD5dBKZ2jpiPMoRhm-ZCnOEl5P3CktcaaNmqcyY3tVlbz8AMQwzik))
* [ ] NIFs
* [ ] LiveViewNative tutorial
* [ ] GenServers (beyond the basics i.e. handle_continue, terminate, etc)
* [ ] Port
* [ ] Timex
* [ ] Wallaby
* [ ] Telemetry
* [ ]  Dynamic Supervisor
* [ ] Node
* [ ] PartitionSupervisor
* [ ] Nimble Publisher
* [ ] Advanced forms
* [ ] Mox
* [ ] Umbrella Projects
* [ ] GenStage
* [ ] Broadway
* [ ] StreamData
* [ ] Flow
* [ ] Plug and Cowboy
* [X] Chat GPT API
* [ ] Nerves
* [ ] Building APIs with Phoenix (no html)
* [ ] Rate Limiting
* [ ] Auth0/OAuth.
* [ ] How to read error messages
* [ ] Problem Solving Techniques
* [ ] Interfacing with Phoenix PubSub from an external source
* [ ] Go deeper into binary and bitstrings
* [ ] Refactoring (Guilded Rose Kata)

**Comment by mvkvc** [comment]
Integrating Bumblebee in a simple text input or image upload API on local CPU

**Comment by BhargavaSwamy** [comment]
@BrooklinJazz I think it would be awesome to include more support for using APIs, especially GPT APIs. While the curriculum briefly covers working with APIs, more examples and exercises with "real-life" APIs would be incredibly beneficial for students. I would love to contribute to this effort with your guidance. Let me know if there's anything I can do to help!

**Comment by BhargavaSwamy** [comment]
And +1 on a tutorial for LiveView Native

**Comment by BrooklinJazz** [comment]
> @BrooklinJazz I think it would be awesome to include more support for using APIs, especially generative APIs like GPT, Whisper and PaLM . While the curriculum briefly covers working with APIs, more examples and exercises with "real-life" APIs would be incredibly beneficial for students. I would love to contribute to this effort with your guidance. Let me know if there's anything I can do to help!

Hey Swamy!

We've started running a Friday morning advanced elixir developers meeting to cover topics like these. If it works for your schedule, I would love to see you there! We're using those meetings to help refine and practice teaching these bonus-topics.

If you're interested in helping out with APIs I have a ticket to change HTTPoison in the API reading -> Finch and Poison -> Json. 

#828 

Simultaneously this would be a good opportunity to redo the material and include more real-life APIs.

What real-life APIs do you think would be a good fit?

**Comment by BrooklinJazz** [comment]
> I've only skimmed the curriculum, but would love to know if Nerves is in there. I would like to work on automation/ioT projects with Raspberry Pi, for example.

Really cool! We don't cover Nerves and instead focus on web development.

However, I think that would make for an interesting bonus topic to have an intro to nerves. Adding it 🙌
