### ISSUE TITLE
Inconsistent underlining in the Blog: Comments exercise

### ISSUE THREAD

**Issue by BrooklinJazz** [DockYard-Academy/curriculum#909]
![image](https://user-images.githubusercontent.com/14877564/226705214-310271b1-54e2-457f-846c-00309866e5f6.png)

belongs to -> belongs_to

**Comment by Mayank2808sharma** [comment]
kindly assign this issue to me

**Comment by Mayank2808sharma** [comment]
Hello @BrooklinJazz 

I have solved this issue.
